/*
    Stworzymy zestaw obiektow do ukazania nastepujacych rzeczy:
        - Role i uprawnienia
        - Hierarchie rol
        - Bazdy danych, schematy
        - Warehouse'y i Resource monitory
        - Masking Policies
        - Tagi
        - RLS
*/
/*
Reset script
*/
USE ROLE ACCOUNTADMIN;
DROP ROLE IF EXISTS BLAZEJ__ADMIN;
DROP ROLE IF EXISTS BLAZEJ__WRITER;
DROP ROLE IF EXISTS BLAZEJ__READER;
DROP DATABASE IF EXISTS BLAZEJ_DB;
DROP WAREHOUSE IF EXISTS BLAZEJ_READER__XS_WH;
DROP WAREHOUSE IF EXISTS BLAZEJ_WRITER__S_WH;
DROP RESOURCE MONITOR IF EXISTS BLAZEJ__USAGE_MONITOR;

/*
Za pomoca roli Security Admin, tworzymy zestaw rol do naszej bazy danych.
Zrobimy prosta hierarchie:
- Admin bazy podlega pod SYSADMIN (Dobra praktyka, zapewnia jasny dostep administratorski do ról)
- Rola __WRITER bedzie sluzyla do operacji DML na obiektach - Podlega pod __ADMIN
- Rola __READER bedzie mogla jedynie odczytywac - Podlega pod __WRITER

                    SYSADMIN
                        |
                    BLAZEJ__ADMIN
                        |
                    BLAZEJ__WRITER
                        |
                    BLAZEJ__READER

*/
USE ROLE SECURITYADMIN;

CREATE ROLE BLAZEJ__ADMIN;
CREATE ROLE BLAZEJ__WRITER;
CREATE ROLE BLAZEJ__READER;


GRANT ROLE BLAZEJ__ADMIN TO ROLE SYSADMIN;
GRANT ROLE BLAZEJ__WRITER TO ROLE BLAZEJ__ADMIN;
GRANT ROLE BLAZEJ__READER TO ROLE BLAZEJ__WRITER;


/*
    Utworzmy teraz obiekty na ktorych bedziemy mogli operowac.
    - Baza danych
        - Nadamy wlasnosc na Bazie roli __ADMIN
    - Schemat w Bazie -> STAGE
    - Schemat w Bazie -> CORE

    - Warehouse rozmiaru XSmall dla roli __READER
    - Warehouse rozmiaru Small dla roli __WRITER
        - Nadamy wlasnosc na Warehouse do roli __ADMIN
*/
USE ROLE SYSADMIN;
CREATE DATABASE BLAZEJ_DB;
GRANT OWNERSHIP ON DATABASE BLAZEJ_DB TO ROLE BLAZEJ__ADMIN;

-- Tworzenie schematu za pomoca roli __ADMIN po nadaniu wlasnosci na Bazie
USE ROLE BLAZEJ__ADMIN;
CREATE SCHEMA BLAZEJ_DB.STAGE;
CREATE SCHEMA BLAZEJ_DB.CORE;

-- Stworzenie warehouse'u
USE ROLE SYSADMIN;
CREATE WAREHOUSE BLAZEJ_READER__XS_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

CREATE WAREHOUSE BLAZEJ_WRITER__S_WH
    WAREHOUSE_SIZE = SMALL
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE;

GRANT OWNERSHIP ON WAREHOUSE BLAZEJ_READER__XS_WH TO ROLE BLAZEJ__ADMIN;
GRANT OWNERSHIP ON WAREHOUSE BLAZEJ_WRITER__S_WH TO ROLE BLAZEJ__ADMIN;


USE ROLE BLAZEJ__ADMIN;
GRANT ALL PRIVILEGES ON WAREHOUSE BLAZEJ_READER__XS_WH TO ROLE BLAZEJ__READER;
GRANT ALL PRIVILEGES ON WAREHOUSE BLAZEJ_WRITER__S_WH TO ROLE BLAZEJ__WRITER;


/*
    Dolaczmy do warehousow Resource Monitor aby sledzily zuzycie
*/

USE ROLE ACCOUNTADMIN;
CREATE RESOURCE MONITOR BLAZEJ__USAGE_MONITOR WITH
    START_TIMESTAMP = IMMEDIATELY
    CREDIT_QUOTA = 10
    FREQUENCY = DAILY
    NOTIFY_USERS = (BLAZEJTECLAW)
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE BLAZEJ_READER__XS_WH
    SET RESOURCE_MONITOR = BLAZEJ__USAGE_MONITOR;

ALTER WAREHOUSE BLAZEJ_WRITER__S_WH
    SET RESOURCE_MONITOR = BLAZEJ__USAGE_MONITOR;
    
/*
    Nadamy nastepnie uprawnienia dla poszczegolnych roli:
    - __READER
        - Odczyt na przyszlych tabelach i widokach w schematach STAGE i CORE
        - Odczyt na przyszlych Stage w schemacie STAGE
        - Odczyt na przyszlych External Tables w schemacie STAGE
    - __WRITER
        - Tworzenie tabel i widokow w schemacie CORE
        - Write na przyszlych tabelach w STAGE i CORE
        - Write na przyszlych Stage w schemacie STAGE
    https://docs.snowflake.com/en/user-guide/security-access-control-privileges
*/
USE ROLE BLAZEJ__ADMIN;

GRANT SELECT ON FUTURE TABLES IN SCHEMA BLAZEJ_DB.STAGE TO ROLE BLAZEJ__READER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA BLAZEJ_DB.STAGE TO ROLE BLAZEJ__READER;
GRANT READ ON FUTURE STAGES IN SCHEMA BLAZEJ_DB.STAGE TO ROLE BLAZEJ__READER;
GRANT SELECT ON FUTURE EXTERNAL TABLES IN SCHEMA BLAZEJ_DB.STAGE TO ROLE BLAZEJ__READER;


GRANT CREATE TABLE, CREATE VIEW ON SCHEMA BLAZEJ_DB.CORE TO ROLE BLAZEJ__WRITER;
GRANT INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA BLAZEJ_DB.STAGE TO ROLE BLAZEJ__WRITER;
GRANT INSERT, UPDATE, TRUNCATE ON FUTURE TABLES IN SCHEMA BLAZEJ_DB.CORE TO ROLE BLAZEJ__WRITER;
GRANT USAGE ON FUTURE STAGES IN SCHEMA BLAZEJ_DB.STAGE TO ROLE BLAZEJ__WRITER;


/*
    W tej czesci zobaczymy co nieco o Row level security i Column level security.
    Na poczatek - stworzmy sobie tabele EMPLOYEE ktora bedzie trzymac informacje takie jak:
        - Imie
        - Nazwisko
        - Telefon
        - Email
        - Deparament
        - Pensja
*/

USE ROLE BLAZEJ__ADMIN;

CREATE OR REPLACE TABLE BLAZEJ_DB.CORE.EMPLOYEE (
    ID INTEGER,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    PHONE TEXT,
    EMAIL TEXT,
    DEPARTMENT TEXT,
    MONTHLY_SALARY NUMBER(38, 2)
);

-- Spopulujmy ja danymi
INSERT INTO BLAZEJ_DB.CORE.EMPLOYEE (
    ID,
    FIRST_NAME,
    LAST_NAME,
    PHONE,
    EMAIL,
    DEPARTMENT,
    MONTHLY_SALARY
)
VALUES
(1, 'Blaise', 'Teclaw', '+48123456789', 'blazej.teclaw@test.com', 'Engineering', 3000),
(2, 'Simon', 'Dum', '+48123456789', 'simon.dum@test.com', 'Engineering', 2000),
(3, 'Matthias', 'Trent', '+48123456789', 'matthias.trent@test.support.com', 'Customer Support', 5000),
(4, 'Lorenz', 'Ipsum', '+48123456789', 'lorenzips@test.support.com', 'Customer Support', 6000),
(5, 'Foo', 'Bar', '+48123456789', 'foo.bar@test.finance.com', 'Finance', 2000),
(6, 'John', 'Wick', '+48123456789', 'blazej.teclaw@test.finance.com', 'Finance', 4000);


USE WAREHOUSE BLAZEJ_READER__XS_WH;
select * from BLAZEJ_DB.CORE.EMPLOYEE;

/*
    Stworzymy sobie teraz 3 oddzielne role dla kadzego oddzialu:
        - Rola ENGINEERING__MANAGER bedzie mogla czytac jedynie dane o Engineering
        - Rola CUSTOMER_SUPPORT__MANAGER bedzie mogla czytac jedynie dane o Customer Support
        - Rola FINANCE__READER bedzie mogla czytac wszystko
*/
USE ROLE SECURITYADMIN;
CREATE ROLE BLAZEJ_ENGINEERING__MANAGER;
CREATE ROLE BLAZEJ_CUSTOMER_SUPPORT__MANAGER;
CREATE ROLE BLAZEJ_FINANCE__READER;
GRANT ROLE BLAZEJ_ENGINEERING__MANAGER TO ROLE BLAZEJ__ADMIN;
GRANT ROLE BLAZEJ_CUSTOMER_SUPPORT__MANAGER TO ROLE BLAZEJ__ADMIN;
GRANT ROLE BLAZEJ_FINANCE__READER TO ROLE BLAZEJ__ADMIN;



USE ROLE BLAZEJ__ADMIN;
GRANT USAGE ON SCHEMA BLAZEJ_DB.CORE TO ROLE BLAZEJ_ENGINEERING__MANAGER;
GRANT USAGE ON SCHEMA BLAZEJ_DB.CORE TO ROLE BLAZEJ_CUSTOMER_SUPPORT__MANAGER;
GRANT USAGE ON SCHEMA BLAZEJ_DB.CORE TO ROLE BLAZEJ_FINANCE__READER;

GRANT SELECT ON TABLE BLAZEJ_DB.CORE.EMPLOYEE TO ROLE BLAZEJ_ENGINEERING__MANAGER;
GRANT SELECT ON TABLE BLAZEJ_DB.CORE.EMPLOYEE TO ROLE BLAZEJ_CUSTOMER_SUPPORT__MANAGER;
GRANT SELECT ON TABLE BLAZEJ_DB.CORE.EMPLOYEE TO ROLE BLAZEJ_FINANCE__READER;

GRANT USAGE ON WAREHOUSE BLAZEJ_READER__XS_WH TO ROLE BLAZEJ_ENGINEERING__MANAGER;
GRANT USAGE ON WAREHOUSE BLAZEJ_READER__XS_WH TO ROLE BLAZEJ_CUSTOMER_SUPPORT__MANAGER;
GRANT USAGE ON WAREHOUSE BLAZEJ_READER__XS_WH TO ROLE BLAZEJ_FINANCE__READER;

CREATE OR REPLACE ROW ACCESS POLICY BLAZEJ_DB.CORE.DEPARTMENT_FILTER
AS (DEPARTMENT TEXT) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('BLAZEJ__ADMIN', 'BLAZEJ__READER', 'BLAZEJ_FINANCE__READER')
    OR (DEPARTMENT = 'Engineering' AND 'BLAZEJ_ENGINEERING__MANAGER' = CURRENT_ROLE())
    OR (DEPARTMENT = 'Customer Support' AND 'BLAZEJ_CUSTOMER_SUPPORT__MANAGER' = CURRENT_ROLE());

ALTER TABLE BLAZEJ_DB.CORE.EMPLOYEE
    ADD ROW ACCESS POLICY BLAZEJ_DB.CORE.DEPARTMENT_FILTER
    ON (DEPARTMENT);


USE ROLE BLAZEJ__READER;
SELECT * FROM BLAZEJ_DB.CORE.EMPLOYEE;

USE ROLE BLAZEJ_ENGINEERING__MANAGER; 
SELECT * FROM BLAZEJ_DB.CORE.EMPLOYEE;

USE ROLE BLAZEJ_CUSTOMER_SUPPORT__MANAGER; 
SELECT * FROM BLAZEJ_DB.CORE.EMPLOYEE;
    